name: 'Blogdown/Hugo setup'
description: 'Set up Hugo + Blogdown'
outputs:
  installed-r-version:
    description: 'The R version installed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
