# action.yml
name: 'Blogdown setup for inSileco'
description: 'Set up R dependencies for inSileco Blog'
# inputs:
#   download_fontawesome:
#     type: boolean
outputs:
  installed-r-version:
    description: 'The R version installed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
