name: 'Blogdown setup for inSileco'
description: 'Set up R dependencies for inSileco Blog'
inputs:
  build_site:
    default: false
outputs:
  installed-r-version:
    description: 'The R version installed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_site }}
