on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Setup blogdown inSileco

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-blogdown-hugo
